import os
from dotenv import load_dotenv
from pathlib import Path
load_dotenv()
BASE_DIR = Path(__file__).resolve().parent
BOT_TOKEN = os.getenv("ZEPH_BOT_TOKEN",
"")
OWNER_ID = int(os.getenv("ZEPH_OWNER_ID","0"))
POLL_INTERVAL = float(os.getenv("POLL_INTERVAL","0.5"))
LOG_LEVEL = os.getenv("LOG_LEVEL","INFO")
SQLITE_PATH = os.getenv("SQLITE_PATH", str(BASE_DIR / "data" / "zeph.db"))
TEMP_DIR = os.getenv("TEMP_DIR", str(BASE_DIR / "temp"))
OCR_SPACE_KEY = os.getenv("OCR_SPACE_KEY",
"")
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY",
"")
REQUIRED_CHANNELS = os.getenv("REQUIRED_CHANNELS","https://t.me/zeph_nova,https://t.me/+TbQFBufetiZmMjE0,https://t.me/+2d0_KkgMHK9kNzNk").split(",")
SESSION_TIMEOUT_SECONDS = int(os.getenv("SESSION_TIMEOUT_SECONDS","15"))
PAYMENT_SESSION_TIMEOUT = int(os.getenv("PAYMENT_SESSION_TIMEOUT","300"))
PREMIUM_DAYS = int(os.getenv("PREMIUM_DAYS","30"))
CAPTION_TEXT = os.getenv("CAPTION_TEXT","Generated by ✞Z£phñøv∆✞ T£cH™")
EMOJI = {"processing":"⚙️","success":"✅","failure":"❌","game_fail":"💀","under_review":"🟡"}
os.makedirs(os.path.dirname(SQLITE_PATH), exist_ok=True)
os.makedirs(TEMP_DIR, exist_ok=True)
USERS_DB = BASE_DIR / "data" / "users.json"
PENDING_PAYMENTS_DB = BASE_DIR / "data" / "payments.json"
COUPONS_DB = BASE_DIR / "data" / "coupons.json"
